server:
  port: 8081

spring:
  application:
    name: spring-webflux-nosql
  data:
    mongodb:
      database: springwebflux_db
      uri: mongodb+srv://yancarloshuacre_db_user:5XfG1D7hZ5MnziV1@cluster0.mfokbuv.mongodb.net/?appName=Cluster0

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html